Fix auto commit

diff --git a/.github/workflows/biome.yml b/.github/workflows/biome.yml
--- a/.github/workflows/biome.yml
+++ b/.github/workflows/biome.yml
@@ -31,14 +31,14 @@ jobs:
         continue-on-error: true
         run: biome ci .
 
-      - name: Auto-fix Formatting (if needed)
-        if: steps.biome_check.outcome == 'failure'
-        run: |
-          biome check --write .
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add .
-          git commit -m "style: auto-format code using Biome" || exit 0
-          git push origin HEAD:master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Auto-fix Formatting (if needed)
+#        if: steps.biome_check.outcome == 'failure'
+#        run: |
+#          biome check --write .
+#          git config --global user.name "github-actions[bot]"
+#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+#          git add .
+#          git commit -m "style: auto-format code using Biome" || exit 0
+#          git push origin HEAD:master
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
